# Generated by Django 3.2.15 on 2022-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_id', models.IntegerField()),
                ('o_id', models.IntegerField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
    ]
