# Generated by Django 3.2.15 on 2022-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_id', models.IntegerField()),
                ('image', models.TextField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'item_details',
                'managed': False,
            },
        ),
    ]
