# Generated by Django 3.2.15 on 2022-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_id', models.IntegerField()),
                ('feedback', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
